{{- if not .Values.slack.tokenFromSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "slack.fullname" . }}-secret
data:
   slackToken: {{ .Values.slack.token | b64enc }}
{{- end }}
